tavily_api_key: ENC[AES256_GCM,data:1qDDovfherMxJ8eyReyHCa3AppMIJ/IeFYNA2WeaygfxG+ZmDLx3Qc2l/pfemS8BciKX+oRT/szfoA==,iv:1ZWvv0lL9/9CQ+HgdNuMGCUDctVlAZrNwzQqCCrgo9s=,tag:zd6cWzjalqIYn9X1o52Bsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bzByczhMdXpKR1JiZFVj
            ZU8zVkhOc1RhUDhHZXdDWTRWRlU2a0QzQ2c0CjBvRU90WGowdHY4TUtCRDc4THJl
            R2w2VVhPN3FWUjJhNEZMekFPL0w5M1kKLS0tIE54N21GNWkyUEZFQkpPQ0VVc0NT
            MlB5WVp4YkR2MVFBcEFKRjNpTVlMZWMK+FL4Nz4ete/CF/WS3zbM5lD6edNLIya4
            5ak1WHwG8yN/LTzQo2VBh6UQKdXMFweb88OCZS6WVxxftnd1OH+PaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fxayq4hptg45dydex68lurplchaczn49j377g5jzfnk4ak40f99spnne2f
    lastmodified: "2026-06-02T10:48:52Z"
    mac: ENC[AES256_GCM,data:Ws834Qpve6K2ZuqKSYbWZgu1lyafvXnS67CLaIlAM/UVQ6wEHN8Kg3BVa95F1JplDs9opZuV3f5wt9+PGLgFsusjHaTnbnSEMS1pCcxKDcBGPAwYKR7z4hk1SpmS+hIlEj1tRS7Pzt3THTdAwoXamUk1bPb49dxCXDAtfV4T1Lw=,iv:mjP7rzvTRCczOsEf/gMYgLz8chqWV5YJojofaA9bwqs=,tag:OdSll8ncSTf6E+8Eal5jlg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
