tavily_api_key: ENC[AES256_GCM,data:1qDDovfherMxJ8eyReyHCa3AppMIJ/IeFYNA2WeaygfxG+ZmDLx3Qc2l/pfemS8BciKX+oRT/szfoA==,iv:1ZWvv0lL9/9CQ+HgdNuMGCUDctVlAZrNwzQqCCrgo9s=,tag:zd6cWzjalqIYn9X1o52Bsw==,type:str]
openrouter_api_key: ENC[AES256_GCM,data:5HMZ807d1hP3nH1Pzs6gr9SYSTN2cpOD97Yh2IAqUslc9KcU7VNSZJfBcFUvCUb2hs8ZKUdTEcxLb9NFy0u0+U2oSI4PCWVOIg==,iv:jkSb6OscxFNjaLI24r4mfjLvaqBh75yBAv2HfHH//nM=,tag:gbIePW11UmrxlkI+IVwPUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bzByczhMdXpKR1JiZFVj
            ZU8zVkhOc1RhUDhHZXdDWTRWRlU2a0QzQ2c0CjBvRU90WGowdHY4TUtCRDc4THJl
            R2w2VVhPN3FWUjJhNEZMekFPL0w5M1kKLS0tIE54N21GNWkyUEZFQkpPQ0VVc0NT
            MlB5WVp4YkR2MVFBcEFKRjNpTVlMZWMK+FL4Nz4ete/CF/WS3zbM5lD6edNLIya4
            5ak1WHwG8yN/LTzQo2VBh6UQKdXMFweb88OCZS6WVxxftnd1OH+PaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fxayq4hptg45dydex68lurplchaczn49j377g5jzfnk4ak40f99spnne2f
    lastmodified: "2026-07-11T04:25:19Z"
    mac: ENC[AES256_GCM,data:MRrpUVf05GkWGQZr4yikXFM2Yh7cvTNMHKpfGC6kB19Du9KMdaI5nn7R9FjGbe1XKw2qgWBu7sE+W+Tp1qWpd/6PSa2N/6I4L1aro3mFLRaoH93ErLm0/2KCHYpWH/FvFlO9Ir/blLQdhpJBafVXsUVi7AdmGsDrr3+NQafC8MI=,iv:5Sfd6NdwVuxYXYjeEeKHK8bdktoc1fqzESxPBLJtsJ0=,tag:uH/ROEchfXTrBIHANCL1vQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
