tavily_api_key: ENC[AES256_GCM,data:1qDDovfherMxJ8eyReyHCa3AppMIJ/IeFYNA2WeaygfxG+ZmDLx3Qc2l/pfemS8BciKX+oRT/szfoA==,iv:1ZWvv0lL9/9CQ+HgdNuMGCUDctVlAZrNwzQqCCrgo9s=,tag:zd6cWzjalqIYn9X1o52Bsw==,type:str]
openrouter_api_key: ENC[AES256_GCM,data:DoSoHHmD5nKBWOGF9uoxSdVnRJ/z5p9AnPd9j+4hNXKSBczn4QUTA+93ULdge1hldH77b1/KNGcx7Yddd6leczM9UznB99QiDg==,iv:trkHw6MRw9WoBVkJAOxDa8dz6oIiXm0vUOocrxxMwR8=,tag:xegwNLlXOONee5T/Y43lWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bzByczhMdXpKR1JiZFVj
            ZU8zVkhOc1RhUDhHZXdDWTRWRlU2a0QzQ2c0CjBvRU90WGowdHY4TUtCRDc4THJl
            R2w2VVhPN3FWUjJhNEZMekFPL0w5M1kKLS0tIE54N21GNWkyUEZFQkpPQ0VVc0NT
            MlB5WVp4YkR2MVFBcEFKRjNpTVlMZWMK+FL4Nz4ete/CF/WS3zbM5lD6edNLIya4
            5ak1WHwG8yN/LTzQo2VBh6UQKdXMFweb88OCZS6WVxxftnd1OH+PaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fxayq4hptg45dydex68lurplchaczn49j377g5jzfnk4ak40f99spnne2f
    lastmodified: "2026-08-22T12:49:50Z"
    mac: ENC[AES256_GCM,data:LI0XQDfmSjNKNPNkoO4LIO2eM5PqYDj5vNkWaJAXN2fDVoajVX3roANOSi/aZ8oR6CQ3moDRaDDap9Pq43ny9cOZBDJpSZprzhS6hpP9JhiNyEPQ2Jm7GQ+RJjAoiJNamyEFDXnD8E8/adhlgdzvqSGoQCnfdVXwx6orcwK6buE=,iv:7kBqQ/cYYB/XNdKryG3dfSIMnlt+/bbsCcAp2WhJD08=,tag:RReMC0N8cnyTIqPzerdnZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
